name: sobral_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.7
  image: ^4.1.3
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  simple_dropdown: ^0.0.3
  image_picker: ^1.0.7
  http: ^1.2.0
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  auto_size_text: ^3.0.0
  share_plus: ^7.2.2
  lottie: ^3.1.2
  fl_chart: ^0.69.0
  cloud_functions: ^4.6.8
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.14.0
  multi_select_flutter: ^4.1.3
  carousel_slider: ^5.0.0
  pdf: ^3.11.1
  printing: ^5.12.0
  pdf_image_renderer: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
    - assets/caf.png
    - assets/pdf/header.png
    - assets/pdf/footer.png
    - assets/sobral.png
    - assets/not_found.json
    - assets/engineer.json
    - assets/environmental.json
    - assets/social.json
    - assets/report.json
    - assets/users.json
